swagger: "2.0"
info:
  title: simple-dsp API
  description: Bid handlers for simple-dsp
  version: 1.0.0
host: localhost:8080
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

paths:
  /bid:
    post:
      summary: Create bid
      description: Create a pending bid for a user's auction
      parameters:
        - in: body
          description: Post auction data to create bid.
          name: payload
          schema: 
            "$ref": "#/definitions/Auction"
      responses:
        '200':
          description: Bid created
        '204':
          description: Bid not created
  /winningnotice?bidid={id}:
    post:
      summary: Impression Notice  
      description: Notify on won bid
      parameters:
        - in: path
          description: The bid to update.
          name: id
          type: string
          required: 
            - id
        - in: body
          description: The bid to update.
          name: payload
          schema: 
            "$ref": "#/definitions/WinNotice"
      responses:
        '412':
          description: Budget limit
        '404':
          description: Bid not found

definitions:
  WinNotice:
    type: object
    required:
      - timestamp
      - price 
    properties:
      timestamp:
        type: number
        example: 28376382
      price:
        type: number
        example: 0.5
  Auction:
    type: object
    required: 
      - id           
      - imp
      - user 
    properties:
      id:
        type: string
        example: "3cb627bf"
      imp:
        type: object
        required:
          - bidfloor
        properties:
          bidfloor: 
            type: number
            example: 0.5
      device:
        type: object
        properties:
          ip: 
            type: string
            example: "100.123.230.3"
      user:
        type: object
        required: 
          - id
        properties:
          id:
            type: string
            example: "f345nf0k"