swagger: "2.0"
info:
  title: simple-dsp API
  description: auction & bid handlers.
  version: 1.0.0
host: localhost:8080
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json

paths:
  /bid:
    post:
      summary: Create bid
      operationId: getBid
      parameters:
        - in: body
          description: The bid to create.
          name: payload
          schema: 
            "$ref": "#/definitions/postPayload"
      responses:
        '200':
          description: Bid created
        '204':
          description: Bid not created

definitions:
  postPayload:
    type: object
    required: true            
    properties:
      id:
        type: string
        required: true
        example: "3cb627bf"
      imp:
        type: object
        required: true
        properties:
          bidfloor: 
            type: number
            required: true
            example: 0.5
      device:
        type: object
        required: true                
        properties:
          ip: 
            type: string
            required: true
            example: "100.123.230.3"
      user:
        type: object
        required: true
        properties:
          id:
            type: string
            required: true
            example: "f345nf0k"